apiVersion: v1 
kind: Service
metadata:
  name: vue001ser 

spec: 
  type: NodePort 
  ports:
  - port: 8000 
    targetPort: 5173 
    protocol: TCP 
    nodePort: 30000 
  selector:
    app: vue001kube
