# ===================================================================
# PersistentVolumeClaim (PVC) - MariaDB 데이터 영속성 보장
# ===================================================================
# PVC는 Pod가 삭제되어도 데이터를 보존하기 위한 영구 저장소 요청서입니다.
# Docker의 Named Volume과 유사한 역할을 합니다.
# ===================================================================

# --- MariaDB 데이터 저장용 PVC ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # PVC 이름 - Deployment에서 이 이름으로 참조합니다
  name: mariadb-data-pvc
spec:
  # 접근 모드 설정
  accessModes:
    # ReadWriteOnce: 단일 노드에서 읽기/쓰기 가능
    # - 하나의 Pod만 이 볼륨을 마운트할 수 있습니다
    # - 데이터베이스처럼 동시 쓰기가 필요 없는 경우 사용
    # 다른 옵션: ReadOnlyMany(여러 노드 읽기 전용), ReadWriteMany(여러 노드 읽기/쓰기)
    - ReadWriteOnce
  
  # 요청할 저장소 리소스
  resources:
    requests:
      # 1GiB의 저장 공간 요청
      # MariaDB의 데이터베이스 파일(/var/lib/mysql)이 저장됩니다
      # 단위: Gi(기비바이트), Mi(메비바이트), Ki(키비바이트)
      storage: 1Gi
  
  # 스토리지 클래스 지정
  # Docker Desktop Kubernetes에서 제공하는 기본 스토리지 클래스
  # 실제로는 호스트(PC)의 디스크에 저장됩니다
  storageClassName: hostpath

---

# --- MariaDB 로그 저장용 PVC ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # 로그 파일 전용 PVC - 데이터와 로그를 분리하여 관리
  name: mariadb-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce  # 단일 노드 읽기/쓰기
  
  resources:
    requests:
      # 500MiB의 저장 공간 요청
      # MariaDB의 로그 파일들(/var/log/mysql)이 저장됩니다
      # - error.log: 에러 로그
      # - general.log: 모든 쿼리 로그
      # - slow.log: 느린 쿼리 로그
      storage: 500Mi
  
  # 데이터 PVC와 동일한 스토리지 클래스 사용
  storageClassName: hostpath

